[project]
name = "mcpserver"
version = "0.1.0"
description = "A simple MCP server to browse the web"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.14.3",
    "crawl4ai>=0.8.0",
    "ddgs>=9.10.0",
    "httpx>=0.28.1",
    "mcp[cli]>=1.26.0",
]
